name: Build DEV

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [registry."${{ secrets.REGISTRY_URL }}"]
              http = true
              insecure = true
      - name: Insecure Docker Repository
        run: |
          sudo truncate -s-2 /etc/docker/daemon.json
          echo ", \"insecure-registries\": [\"${{ secrets.REGISTRY_URL }}\"]}" | sudo tee -a /etc/docker/daemon.json
          cat /etc/docker/daemon.json
          systemctl status docker.service
          sudo systemctl restart docker
      - name: Docker Auth
        run: docker login ${{ secrets.REGISTRY_URL }}
      - name: Build and push AMD64
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/${{ secrets.DOCKER_TAG_DEV }}
          platforms: linux/amd64, linux/arm64
          secrets: |
            "MASTER_URL=${{ secrets.MASTER_URL }}"
            "API_KEY=${{ secrets.API_KEY }}"