name: Build DEV

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: ${{ secrets.REGISTRY_URL }}
      - name: Build and push AMD64
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_TAG_DEV }}
          platforms: linux/amd64, linux/arm64
          secrets: |
            "MASTER_URL=${{ secrets.MASTER_URL }}"
            "API_KEY=${{ secrets.API_KEY }}"